parameters:
  cti_rest_client.resource_locator.class: CTI\RestClientBundle\Services\ResourceLocator
  cti_rest_client.class  : CTI\RestClientBundle\RestClient
  # please override this in your application configuration file
  cti_rest_client_url_base : INTENTIONALLY_BROKEN
  guzzle_client_timeout: 10

services:

  # allows easy location of resources
  cti_rest_client.resource_locator:
    class: %cti_rest_client.resource_locator.class%
    arguments:
      - @kernel

  cti_rest_client.rest_parent :
    class : %cti_rest_client.class%
    arguments :
      - %guzzle_client_timeout%
    calls :
      - [ setLocator, [ @cti_rest_client.resource_locator ] ]
      # example for setting base authentication
      #- [ authenticate, [%api_username%, %api_password%] ]
      # can be uncommented if using "cti/bbox-client-bundle" as a dependency
      #- [ addSubscriber, [@bbox_guzzle_subscriber] ]
      # set the base URL for the api calls
      #- [ setBaseUrl, [%api_base_url%] ]

